### ISSUE TITLE
Re-use tokens

### ISSUE THREAD

**Issue by guysoft** [kensanata/mastodon-archive#71]
Hey,
I want to write a script that turns a Mastodon profile to a blog/recipe page.
Is there a way to get a token once, and then reuse it?
If not, can you point me where it is done in the code, so I can modify it?

Thanks,

**Comment by lapineige** [comment]
@guysoft I am very interested, is that project online somewhere ?

**Comment by guysoft** [comment]
@lapineige not yet, I started looking at Mastodon.py and found very little documentation on how to download all toots/statuses. Then I found mastodon-backup and saw I could generate a json with all the toots.

If I get it to work I will release the source, its for my https://kitch.win/@guysoft .
I found people won't read it outside fediverse because of the CWs.

**Comment by lapineige** [comment]
Ok, feel free to ping me when you have something to test :)

**Comment by kensanata** [comment]
Rereading this more than a year later, I guess there's nothing for mastodon-archive to do, here.
