### ISSUE TITLE
incremental runs of 'mastodon-archive' giving 404s on deleted mentions/replies on STDERR

### ISSUE THREAD

**Issue by IzzySoft** [kensanata/mastodon-archive#92]
I'm running `mastodon-archive archive --with-mentions --with-following "$myacc"`¹ in a daily Cron job. Looks like 2 days ago someone deleted some "mentions". Since then, on every run, I get the following error:

```
Get user info
Indexing 868 statuses...
Indexing 419 favourites...
Indexing 36 bookmarks...
Indexing 871 mentions...
No replies in this archive...
Indexed 1908 statuses...
Counting missing replies...
Missing 120 originals...
Fetching |###############                 | 59/120('Mastodon API returned error', 404, 'Not Found', 'Not Found')
Fetching |################################| 120/120
96 urls in your backup (47 are previews)
Downloading |################################| 96/96
22 urls in your backup (10 are previews)
Downloading |################################| 22/22
```

The `('Mastodon API returned error', 404, 'Not Found', 'Not Found')` is logged on STDERR and thus results in a mail from the Cron job.

**Is there any way to clean that up,** so the error goes away (otherwise I expect that the error line will grow with time) – without "losing data" (e.g. just "breaking the connection" to those 2 missing toots)?

----

¹ basically, `contrib/mastoarch` without archiving followers, so the error more likely comes from `mastodon-archive replies "$myacc"`

**Comment by kensanata** [comment]
I wonder. Looking at the code in question:

```python
    if len(missing) > 0:
        if not "replies" in data:
            replies = []
        else:
            replies = data["replies"]

        bar = Bar('Fetching', max = len(missing))

        for id in missing:
            try:
                status = mastodon.status(id)
                replies.append(status)
            except Exception as e:
                if  "not found" in str(e):
                    pass
                else:
                    print(e, file=sys.stderr)

            bar.next()

        bar.finish()

        data["replies"] = replies
        core.save(status_file, data)
```

Is the problem that the case of the exception changed? The code ignores `"not found"` and in your example it says `"Not Found"`.

```python
>>> "not found" in "Not Found"
False
```

What happens if we change that:

```python
            except Exception as e:
                if  "not found" in str(e) or "Not Found" in str(e):
                    pass
```

**Comment by IzzySoft** [comment]
That seems to do the trick:

```
Counting missing replies...
Missing 133 originals...
Fetching |################################| 133/133
```

**Comment by kensanata** [comment]
Fixed in 0f88336.

**Comment by IzzySoft** [comment]
Thanks!

**Comment by lapineige** [comment]
Strangely, this is not fixed now, and using pip I can't upgrade to that 1.4.3 version that seems to contains the fix.

**Comment by lapineige** [comment]
Oh wait, I don't have the issue while downloading, but when expiring !

**Comment by kensanata** [comment]
@lapineige How about you create a new issue? I'll take a look.
