### ISSUE TITLE
Consider making --with-followers and --with-following on by default?

### ISSUE THREAD

**Issue by fasiha** [kensanata/mastodon-archive#94]
Important background: I just accidentally unfollowed a ton of follows (messing with the API) and am slapping my forehead because my mastodon-archive runs were done without these two flags. So my request may be very biased 😅.

Would it be reasonable to turn these two flags on by default, assuming they're not a burden on the server?

**Comment by kensanata** [comment]
If they are anything like the other calls, the data gets fetched in batches of 40 each. I'm assuming the burden is not terrible, but it's definitely not zero. I also don't think the come in an order we can rely on, so we always fetch all of them, not just the updates.

So… I'm not sure.

**Comment by kensanata** [comment]
I guess it would be cool to write a command that recreates the list of followers based on the messages you wrote, assuming you mentioned each one of them at least once?

**Comment by fasiha** [comment]
Ah I see! Given the non-negligible load this imposes on the server, maybe it's best this isn't on by default. Thanks for consideration!

> assuming you mentioned each one of them at least once

Alas I'm one of these people who follow others without interacting with them 😓
