### ISSUE TITLE
Version check fails on Pleroma instance

### ISSUE THREAD

**Issue by lightnin** [kensanata/mastodon-archive#99]
Greetings and thanks for making this software.
Perhaps there is no intention to support Pleroma, which would be understandable. But I am told that the output archives should be compatible, which makes me suspect that this could work. However, after successful authentication I receive the following error:

<img width="753" alt="Screenshot 2023-04-21 at 21 00 32" src="https://user-images.githubusercontent.com/1538027/233720137-d071fdce-e820-44d9-a1ef-44659b579f66.png">

I wonder if the version check failure is the only issue likely to block successful functioning with Pleroma. This was tested with Pleroma 2.5.1. Is there a way to test this? 

Alternatively, is there a way to encode a backup archive from pleroma (again, I'm assured it is identical to one exported from current versions of Mastodon) such that it could be recognized by mastodon-archive, and used to render html? I have a need to render my bookmarked toots as html for my thesis, and this would seem the best tool for the job. 

Many thanks for any consideration.

**Comment by kensanata** [comment]
I have no idea. I don't do a version check, but the [Mastodon.py](https://github.com/halcy/Mastodon.py) library probably does. It looks like you're trying to download bookmarks. Does Pleroma have bookmarks? If your instance does not have bookmarks, use the `--no-bookmarks` option and try again?

**Comment by lightnin** [comment]
Yep, Pleroma is pretty near identical as far as I can see - does have bookmarks.
I tried the --no-bookmarks flag and was surprised to see that .... it worked! Media download after did too. Even managed to make the html page. Something is henky with the video embeds showing as broken images (even though clicking them does load the video), and the image size formatting is quite weird. But this is great progress - thanks for making and sharing this utility! 
<img width="692" alt="Screenshot 2023-04-22 at 08 22 32" src="https://user-images.githubusercontent.com/1538027/233766741-d4b35bb4-d304-4cc3-b092-c5dc0286a0aa.png">

**Comment by lightnin** [comment]
Thanks for the advice and for making and sharing this cool utility, @kensanata ! Looks like I might have to do some styling work to make the output html easier to view wrt images and video. If I can figure out some better CSS for the photos and videos, is there someplace I should submit a PR?

**Comment by kensanata** [comment]
Right here is fine. 😃
